# Generated by Django 5.0.1 on 2024-02-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='authors',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='month',
            name='filename',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='month',
            name='name',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
