# Generated by Django 5.0.1 on 2024-02-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldays', '0004_year23'),
    ]

    operations = [
        migrations.AddField(
            model_name='year23',
            name='inst',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
